image: atnartur/docker:latest

stages:
  - lint
  - build
  - deploy

lint:
  stage: lint
  image: python:3.8
  before_script: []
  script:
    - pip install -r lint_requirements.txt
    - pre-commit install
    - pre-commit run --all-files
  tags:
    - linux

build:
  stage: build
  script:
    - docker-compose -f docker-compose.prod.yml build app
    - docker-compose -f docker-compose.prod.yml build nginx
  tags:
    - linux

deploy_linux:
  stage: deploy
  script:
    - docker-compose -f docker-compose.prod.yml stop
    - docker-compose -f docker-compose.prod.yml rm -f
    - docker-compose -f docker-compose.prod.yml up -d
  tags:
    - linux
  only:
    - main
