concurrent = 1
check_interval = 0

[[runners]]
  name = "gitlab-runner"
  token = "GR1348941jQvUxthPGQg3LS-j2yz1"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "atnartur/docker:latest"
    privileged = true
    disable_cache = false
    cache_dir = "cache"
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
  [runners.cache]
