version: '3'

services:
  nginx:
    container_name: "nginx"
    privileged: true
    image: nginx:latest
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    depends_on:
      - app
    restart: always
  app:
    container_name: "app"
    privileged: true
    build:
      context: .
      dockerfile: deploy/python/Dockerfile
    depends_on:
      - db
    ports:
    - "8000:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    volumes:
      - media:/app/media
    restart: always

  db:
    container_name: "db"
    privileged: true
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    restart: always


volumes:
  db:
  media:
