version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    build:
      context: deploy
      dockerfile: deploy/nginx/Dockerfile
    depends_on:
      - app
    restart: always
  app:
    build:
      context: deploy
      dockerfile: deploy/python/Dockerfile
    ports:
    - "8000:8000"
    environment:
      DATABASE_HOST: $PROD_DATABASE_HOST
      DATABASE_PORT: 5432
      DATABASE_USER: $PROD_DATABASE_USER
      DATABASE_NAME: $PROD_DATABASE_NAME
      DATABASE_PASSWORD: $PROD_DATABASE_PASSWORD

    volumes:
    - media:/app/media
    restart: always


volumes:
  media:
