"""empty message

Revision ID: 125e16b35258
Revises: eb57bb35b246
Create Date: 2022-06-01 15:50:15.942231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "125e16b35258"
down_revision = "eb57bb35b246"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("housing_category", "description")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "housing_category",
        sa.Column(
            "description", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
