"""empty message

Revision ID: 15e4f4da2045
Revises: 05ac58049d31
Create Date: 2022-05-29 16:59:02.659681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15e4f4da2045"
down_revision = "05ac58049d31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("housing_image", sa.Column("file_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("housing_image", "file_name")
    # ### end Alembic commands ###
