"""empty message

Revision ID: 23d8309fce4b
Revises: 6a726976c60f
Create Date: 2022-04-24 16:14:03.049100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d8309fce4b'
down_revision = '6a726976c60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'housing_history', ['id', 'user_id'])
    op.add_column('housing_review', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'housing_review', ['history_id', 'user_id'])
    op.drop_constraint('housing_review_history_id_fkey', 'housing_review', type_='foreignkey')
    op.create_foreign_key('fk_on_housing_history', 'housing_review', 'housing_history', ['history_id', 'user_id'], ['id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_on_housing_history', 'housing_review', type_='foreignkey')
    op.create_foreign_key('housing_review_history_id_fkey', 'housing_review', 'housing_history', ['history_id'], ['id'])
    op.drop_constraint(None, 'housing_review', type_='unique')
    op.drop_column('housing_review', 'user_id')
    op.drop_constraint(None, 'housing_history', type_='unique')
    # ### end Alembic commands ###
