"""empty message

Revision ID: 274de093abb7
Revises: 0a1e912ce8f2
Create Date: 2022-05-02 12:52:25.296822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "274de093abb7"
down_revision = "0a1e912ce8f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "surname", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user", "_phone_number", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "user", "phone_country_code", existing_type=sa.VARCHAR(length=8), nullable=True
    )
    op.alter_column("user", "birth_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "birth_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column(
        "user", "phone_country_code", existing_type=sa.VARCHAR(length=8), nullable=False
    )
    op.alter_column(
        "user", "_phone_number", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("user", "surname", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
