"""empty message

Revision ID: 2e5745324ef7
Revises: 4d541234f80c
Create Date: 2022-04-24 01:17:51.916703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5745324ef7'
down_revision = '4d541234f80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
