"""empty message

Revision ID: 4d541234f80c
Revises: 936e8c1c0a55
Create Date: 2022-04-24 00:34:11.204485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d541234f80c'
down_revision = '936e8c1c0a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
