"""empty message

Revision ID: 4e6cece77a7a
Revises: 5d5180d011de
Create Date: 2022-04-23 16:12:39.439870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6cece77a7a'
down_revision = '5d5180d011de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('level >= 0'),
    sa.ForeignKeyConstraint(['parent_id'], ['housing_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('characteristic_type', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characteristic_type', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('housing_category')
    # ### end Alembic commands ###
