"""empty message

Revision ID: 515a49d0b71f
Revises: 15e4f4da2045
Create Date: 2022-05-29 19:12:07.130603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "515a49d0b71f"
down_revision = "15e4f4da2045"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "housing_image", "file_name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "housing_image", "file_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
