"""empty message

Revision ID: 5d5180d011de
Revises: c51ea7c3f942
Create Date: 2022-04-23 14:53:09.322673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5180d011de'
down_revision = 'c51ea7c3f942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristic', sa.Column('characteristic_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('characteristic_type_id_fkey', 'characteristic', type_='foreignkey')
    op.create_foreign_key(None, 'characteristic', 'characteristic_type', ['characteristic_type_id'], ['id'])
    op.drop_column('characteristic', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristic', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'characteristic', type_='foreignkey')
    op.create_foreign_key('characteristic_type_id_fkey', 'characteristic', 'characteristic_type', ['type_id'], ['id'])
    op.drop_column('characteristic', 'characteristic_type_id')
    # ### end Alembic commands ###
