"""empty message

Revision ID: 611c57d3e0ad
Revises: 674a14b69c96
Create Date: 2022-04-27 10:42:07.768647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "611c57d3e0ad"
down_revision = "674a14b69c96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
