"""empty message

Revision ID: 674a14b69c96
Revises: b15878f5e3de
Create Date: 2022-04-24 16:28:31.571731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674a14b69c96'
down_revision = 'b15878f5e3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
