"""empty message

Revision ID: 6a726976c60f
Revises: d652328b8b5f
Create Date: 2022-04-24 15:59:57.388313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a726976c60f'
down_revision = 'd652328b8b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
