"""empty message

Revision ID: 7187a1b565a3
Revises: db7cd86247e9
Create Date: 2022-04-23 20:43:38.734972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7187a1b565a3'
down_revision = 'db7cd86247e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'housing', 'housing_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'housing', type_='foreignkey')
    # ### end Alembic commands ###
