"""empty message

Revision ID: 735d1d3bcaea
Revises: 515a49d0b71f
Create Date: 2022-05-29 20:01:06.654529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "735d1d3bcaea"
down_revision = "515a49d0b71f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("housing", "status", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("housing", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("housing", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("housing", "status", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
