"""empty message

Revision ID: a7687c33fd19
Revises: 23d8309fce4b
Create Date: 2022-04-24 16:16:38.817207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7687c33fd19"
down_revision = "23d8309fce4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "housing", "name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "housing", "description", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column("housing", "address", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("housing", "address", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "housing", "description", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "housing", "name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###
