"""empty message

Revision ID: b0e3211650e3
Revises: 7187a1b565a3
Create Date: 2022-04-23 22:51:51.449560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0e3211650e3'
down_revision = '7187a1b565a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('during', postgresql.TSRANGE(), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=False),
    sa.Column('max_nights', sa.Integer(), nullable=False),
    sa.Column('notification_diff_days', sa.Integer(), nullable=False),
    sa.Column('notification_max_time', sa.Time(), nullable=False),
    sa.CheckConstraint('max_nights >= 0'),
    sa.CheckConstraint('min_nights >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'housing', 'housing_type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'housing', 'housing_calendar', ['calendar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'housing', type_='foreignkey')
    op.drop_constraint(None, 'housing', type_='foreignkey')
    op.drop_table('housing_type')
    op.drop_table('housing_calendar')
    # ### end Alembic commands ###
