"""empty message

Revision ID: b120f8f5fd3b
Revises: fa469d7e4b04
Create Date: 2022-04-24 13:44:59.829891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b120f8f5fd3b'
down_revision = 'fa469d7e4b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
