"""empty message

Revision ID: b15878f5e3de
Revises: a7687c33fd19
Create Date: 2022-04-24 16:27:41.204009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15878f5e3de'
down_revision = 'a7687c33fd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
