"""empty message

Revision ID: d4277a906800
Revises: a4c6c3fc95ec
Create Date: 2022-05-02 19:19:35.826937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4277a906800"
down_revision = "a4c6c3fc95ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
