"""empty message

Revision ID: d652328b8b5f
Revises: 6f574c0d7737
Create Date: 2022-04-24 15:54:18.181143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d652328b8b5f"
down_revision = "6f574c0d7737"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chat", "user1_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("chat", "user2_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_unique_constraint(None, "chat", ["user1_id", "user2_id"])
    op.alter_column(
        "chat_message", "content", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "chat_message",
        "message_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "chat_message", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "chat_message", "chat_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_unique_constraint(
        None, "chat_message", ["message_order", "user_id", "chat_id"]
    )
    op.alter_column(
        "housing_review", "content", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "housing_review", "history_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_foreign_key("fk_on_housing", "request", "housing", ["housing_id"], ["id"])
    op.alter_column(
        "user_review", "content", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "user_review", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "user_review", "reviewer_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_unique_constraint(None, "user_review", ["user_id", "reviewer_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_review", type_="unique")
    op.alter_column(
        "user_review", "reviewer_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("user_review", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("user_review", "content", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint("fk_on_housing", "request", type_="foreignkey")
    op.alter_column(
        "housing_review", "history_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "housing_review", "content", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(None, "chat_message", type_="unique")
    op.alter_column(
        "chat_message", "chat_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "chat_message", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "chat_message",
        "message_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        "chat_message", "content", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(None, "chat", type_="unique")
    op.alter_column("chat", "user2_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("chat", "user1_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
