"""empty message

Revision ID: d86fa18dac7c
Revises: 72c0e4dbe1c3
Create Date: 2022-05-10 10:34:32.357672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d86fa18dac7c"
down_revision = "72c0e4dbe1c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
