"""empty message

Revision ID: db7cd86247e9
Revises: 4e6cece77a7a
Create Date: 2022-04-23 16:28:37.959326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7cd86247e9'
down_revision = '4e6cece77a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
