"""empty message

Revision ID: fa469d7e4b04
Revises: fb41efa3d98f
Create Date: 2022-04-24 13:06:46.917910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa469d7e4b04'
down_revision = 'fb41efa3d98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
