"""empty message

Revision ID: fb41efa3d98f
Revises: 2e5745324ef7
Create Date: 2022-04-24 12:44:32.072990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb41efa3d98f'
down_revision = '2e5745324ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
